- name: Deploy app container on remote server
  hosts: all
  become: true
  tasks:
    - name: Stop old container (if any)
      shell: docker rm -f myapp || true

    - name: Run new container
      shell: docker run -d --name myapp -p 80:5000 myapp:latest
